version: '1.0.{build}'  
image: 
  - Visual Studio 2017
  - Ubuntu
environment:  
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  my_variable:
    secure: FgZC5CV7j5zokY7hkshgaZBkzN3XISYBv/NnLvwiF0ZO3cSuYcv1GiuePaGjTfmD
build_script:  
- ps: "dotnet --version\ndotnet restore \ndotnet publish  --runtime win-x64 -c Release\ndotnet publish  --runtime linux-x64 -c Release\n\n[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\" ; \nInvoke-WebRequest https://github.com/dgiagio/warp/releases/download/v0.3.0/windows-x64.warp-packer.exe -OutFile \"warp-packer.exe\"\n\ndir\n.\\warp-packer --arch windows-x64 --input_dir bin/Release/netcoreapp2.1/win-x64/publish --exec AzureHelper.exe --output AzureHelper.exe"
- sh: "dotnet publish  --runtime linux-x64 -c Release\ncurl -Lso warp-packer https://github.com/dgiagio/warp/releases/download/v0.3.0/linux-x64.warp-packer\nchmod +x warp-packer\n./warp-packer --arch linux-x64 --input_dir bin/Release/netcoreapp2.1/linux-x64/publish --exec AzureHelper --output AzureHelper"

test: off  
artifacts:
- path: AzureHelper.exe
  name: win-x64.azure-helper
- path: AzureHelper
  name: linux-x64.azure-helper

deploy:
  release: 1.0-v$(appveyor_build_version)
  description: 'Azure helper new version'
  provider: GitHub
  auth_token:
    secure: %my_variable% # your encrypted token from GitHub
  artifact: AzureHelper.exe;AzureHelper           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
