version: '{build}'  
image: 
  - Visual Studio 2017
  - Ubuntu
environment:  
  APPVEYOR_YML_DISABLE_PS_LINUX: true

branches:
  only:
    - master

build_script:  
- ps: "dotnet --version\ndotnet restore \ndotnet publish  --runtime win-x64 -c Release\ndotnet publish  --runtime linux-x64 -c Release\n\n[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\" ; \nInvoke-WebRequest https://github.com/dgiagio/warp/releases/download/v0.3.0/windows-x64.warp-packer.exe -OutFile \"warp-packer.exe\"\n\ndir\n.\\warp-packer --arch windows-x64 --input_dir bin/Release/netcoreapp2.1/win-x64/publish --exec tfcloud.exe --output win-x64.tfcloud.exe"
- sh: "dotnet publish  --runtime linux-x64 -c Release\ncurl -Lso warp-packer https://github.com/dgiagio/warp/releases/download/v0.3.0/linux-x64.warp-packer\nchmod +x warp-packer\n./warp-packer --arch linux-x64 --input_dir bin/Release/netcoreapp2.1/linux-x64/publish --exec tfcloud --output linux-x64.tfcloud"

test: off  
artifacts:
- path: win-x64.tfcloud.exe
  name: win-x64.tfcloud.exe
- path: linux-x64.tfcloud
  name: linux-x64.tfcloud

deploy:
  release: 1.0-v$(APPVEYOR_BUILD_VERSION)
  description: 'Azure helper new version'
  provider: GitHub
  auth_token:
    secure: FgZC5CV7j5zokY7hkshgaZBkzN3XISYBv/NnLvwiF0ZO3cSuYcv1GiuePaGjTfmD # your encrypted token from GitHub
  artifact: win-x64.tfcloud.exe;linux-x64.tfcloud           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
